# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This workflow will:
# - Download a prebuilt Ruby version
# - Install dependencies
# - Create and migrate the test database
# - Run tests with Rake
#
# For more information: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]  # Trigger on push to master
  pull_request:
    branches: [ master ]  # Trigger on PRs targeting master

jobs:
  test:
    runs-on: ubuntu-latest  # Run job on latest Ubuntu runner

    services:
      postgres:
        image: postgres:17.4  # Use PostgreSQL version 17.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432  # Expose DB port

        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        # Do not place inline comments inside the 'options' value block!
        # These options:
        # - Use tmpfs to improve DB speed (RAM-only)
        # - Add a health check so the service is "ready" before Rails connects

    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPORT: 5432
      PGPASSWORD: postgres
      RAILS_ENV: test  # Set Rails environment to 'test'

    steps:
      - uses: actions/checkout@v2  # Clone repo into the runner
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'  # Set Ruby version; must be in quotes
      - name: Install dependencies
        run: bundle install  # Install gems
      - name: Create DB
        run: bin/rails db:create db:migrate  # Create and migrate test DB
      - name: Run tests
        run: bundle exec rake  # Run test suite (via Rake)
